# Generated by Django 5.1.3 on 2024-12-18 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_sys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filedata',
            name='key',
            field=models.CharField(default='default_key', max_length=32),
        ),
        migrations.AlterField(
            model_name='filedata',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
