# Generated by Django 5.1.3 on 2024-12-18 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_sys', '0003_alter_filedata_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='filedata',
            name='nonce',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='filedata',
            name='tag',
            field=models.CharField(default='', max_length=255),
        ),
    ]
