# Generated by Django 5.1.3 on 2024-12-18 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_sys', '0004_filedata_nonce_filedata_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filedata',
            name='nonce',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='filedata',
            name='tag',
            field=models.CharField(max_length=255),
        ),
    ]
